#!/usr/bin/env python3
"""Build a 585-cell checkpoint catalog from the imported A100 matrix run.

The accepted A100 full-matrix run retained its trained checkpoints in S3 but no
prediction bundles, so the primary-identity forecasts have to be regenerated by
an export-only replay. This script turns the downloaded checkpoint tree into the
catalog that replay validates, binding every cell to the A100 run's own
completed status and to the local file size and SHA-256.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import time
from pathlib import Path

import sys

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ts_rag.matrix import load_manifest
from ts_rag.matrix_checkpoints import validate_selected_checkpoint_catalog


def sha256_file(path, chunk_size=8 * 1024 * 1024):
    digest = hashlib.sha256()
    with Path(path).open("rb") as source:
        while chunk := source.read(chunk_size):
            digest.update(chunk)
    return digest.hexdigest()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--source-summary", required=True)
    parser.add_argument("--checkpoint-root", required=True)
    parser.add_argument("--source-revision", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    manifest = load_manifest(args.manifest)
    summary = json.loads(Path(args.source_summary).read_text())
    states = {row["cell_id"]: row for row in summary["cell_states"]}
    root = Path(args.checkpoint_root)

    checkpoints = {}
    for row in manifest:
        cell_id = row["id"]
        state = states.get(cell_id)
        if state is None or state.get("state") != "completed":
            raise SystemExit(f"Source run has no completed cell for {cell_id}")
        family, dataset, model, horizon = cell_id.split("/")
        matches = sorted(
            (root / family / dataset / model / f"pl{horizon}").glob(
                "seed*/checkpoint.pth"
            )
        )
        if len(matches) != 1:
            raise SystemExit(
                f"Expected exactly one checkpoint for {cell_id}, found {len(matches)}"
            )
        path = matches[0]
        if path.is_symlink() or not path.is_file():
            raise SystemExit(f"Checkpoint is not a regular file: {path}")
        checkpoints[cell_id] = {
            "artifact_dir": state.get("artifact_dir"),
            "checkpoint_mode": "trained",
            "file_size": path.stat().st_size,
            "numerical_recovery": None,
            "numerical_recovery_cohort": None,
            "reason": None,
            "relative_path": str(path.relative_to(root)),
            "result_path": None,
            "sha256": sha256_file(path),
            "source_revision": args.source_revision,
            "staging_mode": "downloaded",
            "usable": True,
        }
        print(f"{len(checkpoints)}/{len(manifest)} {cell_id}", flush=True)

    catalog = {
        "checkpoint_count": len(checkpoints),
        "checkpoint_path_root": str(root.resolve()),
        "checkpoint_stage_root": None,
        "checkpoints": checkpoints,
        "generated_unix": time.time(),
        "hashes_included": True,
        "missing_count": 0,
        "missing_selected": [],
        "missing_selected_count": 0,
        "numerical_recovery": None,
        "numerical_recovery_cohort": None,
        "numerical_recovery_receipt": None,
        "project_root": None,
        "schema_version": 1,
        "selected_count": len(checkpoints),
        "source_revision": args.source_revision,
        "source_run": {
            "summary": str(Path(args.source_summary).resolve()),
            "summary_sha256": sha256_file(args.source_summary),
        },
        "summary_generated_unix": summary.get("generated_unix"),
        "usable_count": len(checkpoints),
    }
    validate_selected_checkpoint_catalog(
        catalog,
        [row["id"] for row in manifest],
        args.source_revision,
        require_hashes=True,
    )
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.output).write_text(json.dumps(catalog, indent=2, sort_keys=True))
    print(f"wrote {args.output} with {len(checkpoints)} checkpoints")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
